package io.quarkiverse.desktop.swt.deployment;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Properties;

import org.junit.jupiter.api.Test;

/**
 * The descriptor of the extension ({@code META-INF/quarkus-extension.properties} of the runtime module, generated by the
 * {@code quarkus-extension-maven-plugin}). The JVM of dev mode starts before any build step runs, with the JVM options
 * of the descriptors of the extensions : the one of this extension enables the native access, so that the JDK (24 and
 * later) does not warn about the {@code System.load} calls of SWT.
 */
class ExtensionDescriptorTest {

    static final String DESCRIPTOR = "META-INF/quarkus-extension.properties";

    static final String DEPLOYMENT_ARTIFACT = "io.quarkiverse.desktop:quarkus-desktop-swt-deployment:";

    @Test
    void devModeEnablesTheNativeAccess() throws IOException {
        Properties descriptor = descriptor();
        assertEquals("ALL-UNNAMED", descriptor.getProperty("dev-mode.jvm-option.std.enable-native-access"),
                descriptor.toString());
    }

    /**
     * The descriptor of this extension, among the ones of the extensions of the test class path : the one whose
     * deployment artifact is this module.
     */
    static Properties descriptor() throws IOException {
        List<Properties> descriptors = new ArrayList<>();
        List<URL> urls = new ArrayList<>();
        for (URL url : Collections.list(ExtensionDescriptorTest.class.getClassLoader().getResources(DESCRIPTOR))) {
            Properties properties = new Properties();
            try (InputStream in = url.openStream()) {
                properties.load(in);
            }
            if (properties.getProperty("deployment-artifact", "").startsWith(DEPLOYMENT_ARTIFACT)) {
                descriptors.add(properties);
                urls.add(url);
            }
        }
        assertEquals(1, descriptors.size(), "The descriptors of the Desktop SWT extension : " + urls);
        return descriptors.get(0);
    }
}
