package io.quarkiverse.desktop.awt.it;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.zip.ZipFile;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledOnOs;
import org.junit.jupiter.api.condition.OS;

/**
 * Checks the files of the native executable : the quarkus-awt substitutions removed from the native build, the libraries
 * next to it ; on Windows, the application manifest and the shim exports ; on macOS, the frameworks and the library
 * search path of the executable.
 */
@EnabledOnOs({ OS.WINDOWS, OS.LINUX, OS.MAC })
public class NativeExecutableIT {

    private static Path executable;
    private static Path directory;

    @BeforeAll
    static void executable() {
        String path = System.getProperty("native.image.path");
        executable = Path.of(OS.WINDOWS.isCurrentOs() && !path.endsWith(".exe") ? path + ".exe" : path);
        directory = executable.toAbsolutePath().getParent();
        assertTrue(Files.isRegularFile(executable), executable + " not found");
    }

    @Test
    @EnabledOnOs(OS.WINDOWS)
    void manifestIsEmbedded() throws IOException {
        String content = new String(Files.readAllBytes(executable), StandardCharsets.ISO_8859_1);
        assertTrue(content.contains("Microsoft.Windows.Common-Controls"), "no common controls manifest");
        assertTrue(content.contains("PerMonitorV2"), "no DPI awareness in the manifest");
        // quarkus.desktop.awt.windows.subsystem=console (default)
        assertEquals(3, PeFile.read(executable).subsystem(), "not a console executable");
    }

    @Test
    @EnabledOnOs(OS.WINDOWS)
    void awtLibrariesAndVisualCppRuntimeAreNextToTheExecutable() {
        for (String library : List.of("awt.dll", "fontmanager.dll", "freetype.dll", "javajpeg.dll", "lcms.dll", "java.dll",
                "jvm.dll", "msvcp140.dll", "vcruntime140.dll", "vcruntime140_1.dll")) {
            assertTrue(Files.isRegularFile(directory.resolve(library)), library + " not found in " + directory);
        }
    }

    /**
     * The JDK libraries that AWT loads from the directory of a Linux executable (copied by GraalVM), the X11 toolkit
     * included, and the {@code libjava} and {@code libjvm} shims generated by GraalVM.
     */
    @Test
    @EnabledOnOs(OS.LINUX)
    void awtLibrariesAreNextToTheExecutable() {
        for (String library : List.of("libawt.so", "libawt_xawt.so", "libfontmanager.so", "libjavajpeg.so", "liblcms.so",
                "libmlib_image.so", "libjava.so", "libjvm.so")) {
            assertTrue(Files.isRegularFile(directory.resolve(library)), library + " not found in " + directory);
        }
    }

    /**
     * The JDK libraries that AWT loads from the directory of a macOS executable (copied by GraalVM 25.1 and later), the
     * Cocoa toolkit ({@code libawt_lwawt}, {@code libosxapp}) and the Aqua look and feel ({@code libosxui}, which draws
     * the AWT components) included, and the {@code libjava} and {@code libjvm} shims generated by GraalVM.
     */
    @Test
    @EnabledOnOs(OS.MAC)
    void macLibrariesAreNextToTheExecutable() {
        for (String library : List.of("libawt.dylib", "libawt_lwawt.dylib", "libosxapp.dylib", "libosxui.dylib",
                "libfontmanager.dylib", "libfreetype.dylib", "libjavajpeg.dylib", "liblcms.dylib", "libmlib_image.dylib",
                "libjava.dylib", "libjvm.dylib")) {
            assertTrue(Files.isRegularFile(directory.resolve(library)), library + " not found in " + directory);
        }
    }

    /**
     * The macOS executable links CoreFoundation (the Cocoa run loop of the first thread) and looks for its libraries in
     * its own directory ({@code @loader_path}).
     */
    @Test
    @EnabledOnOs(OS.MAC)
    void macExecutableLinksCoreFoundationAndLoadsTheLibrariesNextToIt() throws IOException, InterruptedException {
        String libraries = run("otool", "-L", executable.toString());
        assertTrue(libraries.contains("/CoreFoundation.framework/"), "CoreFoundation not linked :\n" + libraries);
        String loadCommands = run("otool", "-l", executable.toString());
        assertTrue(loadCommands.contains("LC_RPATH") && loadCommands.contains("@loader_path"),
                "no @loader_path run path");
    }

    /**
     * The macOS executable declares the minimum macOS version and the SDK version of the java launcher of the JDK
     * (quarkus.desktop.awt.macos.jdk-build-version) : the same window appearance as in JVM mode, and it starts on the
     * macOS versions of the JDK, not only on the version of the SDK of the Xcode tools.
     */
    @Test
    @EnabledOnOs(OS.MAC)
    void macExecutableHasTheBuildVersionOfTheJavaLauncher() throws IOException, InterruptedException {
        Path jdkHome = builderJdkHome();
        assertEquals(buildVersion(jdkHome.resolve("bin").resolve("java")), buildVersion(executable),
                "the build version of the java launcher of " + jdkHome);
    }

    /**
     * The JDK of the native build, chosen as the extension chooses it (DesktopAwtProcessor.builderJdkHome) and as Quarkus
     * chooses its native-image : quarkus.native.graalvm-home (QUARKUS_NATIVE_GRAALVM_HOME, GRAALVM_HOME by default),
     * then quarkus.native.java-home (QUARKUS_NATIVE_JAVA_HOME, java.home by default), each when it has
     * bin/native-image, else the first native-image of the PATH (links resolved, up to the directory of the release file
     * of the JDK), else java.home. Failsafe gives the test the -D properties of the Maven command line, not the
     * application.properties : set the homes there with -D or the environment.
     */
    private static Path builderJdkHome() throws IOException {
        String javaHome = System.getProperty("java.home");
        String[] homes = { first(System.getProperty("quarkus.native.graalvm-home"),
                System.getenv("QUARKUS_NATIVE_GRAALVM_HOME"), System.getenv("GRAALVM_HOME")),
                first(System.getProperty("quarkus.native.java-home"), System.getenv("QUARKUS_NATIVE_JAVA_HOME"),
                        javaHome) };
        for (String home : homes) {
            if (home != null && Files.isRegularFile(Path.of(home, "bin", "native-image"))) {
                return Path.of(home);
            }
        }
        String path = System.getenv("PATH");
        for (String directory : path == null ? new String[0] : path.split(java.io.File.pathSeparator)) {
            Path candidate = directory.isBlank() ? null : Path.of(directory, "native-image");
            if (candidate != null && Files.isRegularFile(candidate)) {
                // the first native-image of the PATH, the one Quarkus runs : GraalVM links <home>/bin/native-image to
                // <home>/lib/svm/bin/native-image, the home is at most 3 directories above the real bin directory,
                // else the parent of that bin directory (DesktopAwtProcessor.JDK_HOME_DEPTH)
                Path bin = candidate.toRealPath().getParent();
                Path home = bin;
                for (int i = 0; home != null && i <= 3; i++, home = home.getParent()) {
                    if (Files.isRegularFile(home.resolve("release"))) {
                        return home;
                    }
                }
                return bin.getParent();
            }
        }
        return Path.of(javaHome);
    }

    /**
     * The first value that is set, as SmallRye Config resolves a property (system property, environment variable,
     * default).
     */
    private static String first(String... values) {
        for (String value : values) {
            if (value != null && !value.isBlank()) {
                return value;
            }
        }
        return null;
    }

    /**
     * The minimum macOS version and the SDK version of a Mach-O file ({@code otool -l}).
     */
    private static List<String> buildVersion(Path file) throws IOException, InterruptedException {
        List<String> versions = new ArrayList<>();
        String command = "";
        for (String line : run("otool", "-l", file.toString()).lines().toList()) {
            String trimmed = line.trim();
            if (trimmed.startsWith("cmd ")) {
                command = trimmed.substring(4);
            } else if (command.equals("LC_BUILD_VERSION") && (trimmed.startsWith("minos ") || trimmed.startsWith("sdk "))
                    || command.equals("LC_VERSION_MIN_MACOSX")
                            && (trimmed.startsWith("version ") || trimmed.startsWith("sdk "))) {
                // not the versions of the tools that built the file (LC_BUILD_VERSION "tool ... version ...")
                versions.add(trimmed);
            }
        }
        assertFalse(versions.isEmpty(), "no build version in " + file);
        return versions;
    }

    /**
     * awt.dll imports jio_snprintf from java.dll : the shim generated by GraalVM 25.0 only exports it when javajpeg is
     * registered (quarkus-awt registers it).
     */
    @Test
    @EnabledOnOs(OS.WINDOWS)
    void javaShimExportsJioSnprintf() throws IOException {
        Set<String> exports = PeFile.read(directory.resolve("java.dll")).exports();
        assertTrue(exports.contains("jio_snprintf"), "java.dll exports " + exports);
    }

    /**
     * The quarkus-awt substitutions that break AWT GUI applications or disable Type 1 fonts are removed on every
     * platform.
     */
    @Test
    void quarkusAwtGuiBlockersAreNotInTheNativeBuild() throws IOException {
        List<Path> jars = new ArrayList<>();
        try (DirectoryStream<Path> sourceJars = Files.newDirectoryStream(directory, "*-native-image-source-jar")) {
            for (Path sourceJar : sourceJars) {
                try (DirectoryStream<Path> libs = Files.newDirectoryStream(sourceJar.resolve("lib"),
                        "*io.quarkus.quarkus-awt-*.jar")) {
                    libs.forEach(jars::add);
                }
            }
        }
        assertFalse(jars.isEmpty(), "quarkus-awt jar of the native build not found");
        for (Path jar : jars) {
            try (ZipFile zip = new ZipFile(jar.toFile())) {
                for (String entry : List.of("Target_sun_awt_windows_WObjectPeer", "Target_sun_java2d_windows_WindowsFlags",
                        "Target_sun_awt_windows_WToolkit", "Target_sun_font_Type1Font",
                        // the macOS ones, of the Quarkus versions whose quarkus-awt supports macOS
                        "Target_sun_awt_PlatformGraphicsInfo_Mac", "Target_sun_lwawt_macosx_LWCToolkit",
                        "Target_sun_awt_CGraphicsEnvironment", "Target_sun_print_PlatformPrinterJobProxy")) {
                    assertTrue(zip.getEntry("io/quarkus/awt/runtime/" + entry + ".class") == null, entry + " in " + jar);
                }
                assertTrue(zip.getEntry("io/quarkus/awt/runtime/JDKSubstitutions.class") != null,
                        "JDKSubstitutions removed from " + jar);
            }
        }
    }

    /**
     * The standard output of a command, which must succeed.
     */
    private static String run(String... command) throws IOException, InterruptedException {
        Process process = new ProcessBuilder(command).redirectErrorStream(true).start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        assertEquals(0, process.waitFor(), String.join(" ", command) + " failed :\n" + output);
        return output;
    }

    /**
     * The few parts of a PE (Windows executable or library) file read by the tests.
     */
    record PeFile(int subsystem, Set<String> exports) {

        static PeFile read(Path file) throws IOException {
            ByteBuffer pe = ByteBuffer.wrap(Files.readAllBytes(file)).order(ByteOrder.LITTLE_ENDIAN);
            int header = pe.getInt(0x3c);
            assertEquals(0x4550, pe.getInt(header), "not a PE file");
            int coff = header + 4;
            int sections = Short.toUnsignedInt(pe.getShort(coff + 2));
            int optionalSize = Short.toUnsignedInt(pe.getShort(coff + 16));
            int optional = coff + 20;
            assertEquals(0x20b, Short.toUnsignedInt(pe.getShort(optional)), "not a PE32+ file");
            int subsystem = Short.toUnsignedInt(pe.getShort(optional + 68));
            int exportRva = pe.getInt(optional + 112);
            int sectionTable = optional + optionalSize;
            Set<String> exports = new HashSet<>();
            if (exportRva != 0) {
                int directory = offset(pe, sectionTable, sections, exportRva);
                int names = pe.getInt(directory + 24);
                int nameTable = offset(pe, sectionTable, sections, pe.getInt(directory + 32));
                for (int i = 0; i < names; i++) {
                    int name = offset(pe, sectionTable, sections, pe.getInt(nameTable + 4 * i));
                    StringBuilder symbol = new StringBuilder();
                    for (int c = pe.get(name); c != 0; c = pe.get(++name)) {
                        symbol.append((char) c);
                    }
                    exports.add(symbol.toString());
                }
            }
            return new PeFile(subsystem, exports);
        }

        private static int offset(ByteBuffer pe, int sectionTable, int sections, int rva) {
            for (int i = 0; i < sections; i++) {
                int section = sectionTable + 40 * i;
                int virtualSize = pe.getInt(section + 8);
                int virtualAddress = pe.getInt(section + 12);
                int rawSize = pe.getInt(section + 16);
                if (rva >= virtualAddress && rva < virtualAddress + Math.max(virtualSize, rawSize)) {
                    return rva - virtualAddress + pe.getInt(section + 20);
                }
            }
            throw new IllegalArgumentException("RVA " + Integer.toHexString(rva) + " not in a section");
        }
    }
}
