package io.quarkiverse.desktop.showcase.pages.images;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * The image resources of the images pages ({@code src/main/resources/showcase/text-images/images/}) are generated by
 * this class (no hand-crafted binary) : {@link #generate(Path)} writes them from the computed test images of
 * {@link ImagesSupport}. It was run once with the JDK of the showcase (see the report of the page author) ; the pages
 * check that the decoded resources equal the images computed at run time.
 * <p>
 * The same bytes are also produced at run time by {@link #png()}, {@link #gif()}, {@link #jpeg()} and {@link #xbm()}.
 */
public final class ImageAssets {

    public static final String DIR = "/showcase/text-images/images/";
    public static final String PNG = DIR + "sample.png";
    public static final String GIF = DIR + "sample.gif";
    public static final String JPEG = DIR + "sample.jpg";
    public static final String XBM = DIR + "sample.xbm";

    static final int W = 96;
    static final int H = 64;

    private ImageAssets() {
    }

    /**
     * Writes the resources into {@code dir} (e.g. {@code src/main/resources/showcase/text-images/images}).
     */
    public static void generate(Path dir) throws IOException {
        Files.createDirectories(dir);
        Files.write(dir.resolve("sample.png"), png());
        Files.write(dir.resolve("sample.gif"), gif());
        Files.write(dir.resolve("sample.jpg"), jpeg());
        Files.write(dir.resolve("sample.xbm"), xbm());
    }

    static BufferedImage pngImage() {
        return ImagesSupport.pattern(W, H, BufferedImage.TYPE_INT_RGB);
    }

    static byte[] png() throws IOException {
        return ImageIoFormatsPage.write(pngImage(), "png", p -> {
        });
    }

    static BufferedImage gifImage() {
        return ImagesSupport.indexed(W, H, 8, -1);
    }

    static byte[] gif() throws IOException {
        return ImageIoFormatsPage.write(gifImage(), "gif", p -> {
        });
    }

    static BufferedImage jpegImage() {
        return ImagesSupport.photo(W, H);
    }

    static byte[] jpeg() throws IOException {
        return ImageIoFormatsPage.write(jpegImage(), "jpeg", p -> {
        });
    }

    /**
     * An X bitmap (text) of the binary test image : bit 1 = foreground (black).
     */
    static byte[] xbm() {
        BufferedImage image = ImagesSupport.binary(W, H);
        StringBuilder sb = new StringBuilder();
        sb.append("#define sample_width ").append(W).append('\n');
        sb.append("#define sample_height ").append(H).append('\n');
        sb.append("static char sample_bits[] = {\n");
        int bytesPerRow = (W + 7) / 8;
        int count = 0;
        for (int y = 0; y < H; y++) {
            for (int b = 0; b < bytesPerRow; b++) {
                int value = 0;
                for (int bit = 0; bit < 8; bit++) {
                    int x = b * 8 + bit;
                    // X bitmaps : least significant bit first ; the binary image has 1 = white
                    if (x < W && image.getRaster().getSample(x, y, 0) == 0) {
                        value |= 1 << bit;
                    }
                }
                sb.append(String.format("0x%02x", value));
                count++;
                if (count < bytesPerRow * H) {
                    sb.append(count % 12 == 0 ? ",\n" : ", ");
                }
            }
        }
        sb.append(" };\n");
        return sb.toString().getBytes(StandardCharsets.US_ASCII);
    }

    /**
     * The expected pixels of the XBM : black where the bit is set, transparent white elsewhere (the Toolkit decoder
     * uses a 2 color palette whose white entry is transparent).
     */
    static BufferedImage xbmExpected() {
        BufferedImage image = ImagesSupport.binary(W, H);
        BufferedImage out = new BufferedImage(W, H, BufferedImage.TYPE_INT_ARGB);
        for (int y = 0; y < H; y++) {
            for (int x = 0; x < W; x++) {
                out.setRGB(x, y, image.getRaster().getSample(x, y, 0) == 0 ? 0xFF000000 : 0x00FFFFFF);
            }
        }
        return out;
    }
}
